site_name: IHC - Projeto de Avaliação da PCDF

repo_name: 2022.2-PCDF
repo_url: https://github.com/Interacao-Humano-Computador/2022.2-PCDF

theme:
  name: material
  logo: assets/icons/logo-pcdf.png
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.emoji

nav:
  - Início: index.md
  - Planejamento:
      - Escolha do site: escolha_do_site.md
      - Cronograma: cronograma.md
      - Processo de design: processo_de_design.md
      - Ferramentas: ferramentas.md
  - Análise de Requisitos:
    - Perfil de Usuário: analise-de-requisitos/perfil_usuario.md
    - Personas: analise-de-requisitos/personas.md
    - Análise de Tarefas: analise-de-requisitos/analise_de_tarefas.md
    - Aspectos Éticos: analise-de-requisitos/aspectos_eticos.md
    - Princípios Gerais do Projeto: analise-de-requisitos/principios_e_diretrizes.md
    - Metas de usabilidade: analise-de-requisitos/metas_de_usabilidade.md
    - Guia de Estilo: analise-de-requisitos/guia_de_estilo.md
    - Características da Plataforma do Projeto: analise-de-requisitos/carac_plat_proj.md
  - Design, Avaliação e Planejamento: 
    - Nível 1:
      - Framework DECIDE: design-avaliacao-desenvolvimento/nivel1/framework_decide.md
      - Planejamento da Avaliação do Storyboard: design-avaliacao-desenvolvimento/nivel1/planejamento-avaliacao-storyboard.md
      - Questões Práticas: design-avaliacao-desenvolvimento/nivel1/questoes_praticas.md
      - Questões Éticas: design-avaliacao-desenvolvimento/nivel1/questoes_eticas.md
      - Planejamento da Análise de Tarefas: design-avaliacao-desenvolvimento/nivel1/Planejamento_Analise_Tarefas.md
    - Nível 2:
      - Relato dos Resultados do Storyboard: design-avaliacao-desenvolvimento/nivel2/avaliacao_do_storyboard.md
      - Planejamento e Relato do Planejamento do Protótipo de Papel: design-avaliacao-desenvolvimento/nivel2/planejamento-avaliacao-prototipo.md
  - Reuniões:
    - Reunião01: Atas/Ata1.md
    - Reunião02: Atas/Ata2.md
    - Reunião03: Atas/Ata3.md
    - Reunião04: Atas/Ata4.md
    - Reunião05: Atas/Ata5.md
    - Reunião06: Atas/Ata6.md
    - Reunião07: Atas/Ata7.md
  - Apresentações:
    - Apresentação-1: apresentacoes/apresentacao-01.md 
    - Apresentação-2: apresentacoes/apresentacao-02.md 
    - Apresentação-3: apresentacoes/apresentacao-03.md 
    - Apresentação-4: apresentacoes/apresentacao-04.md 