site_name: IHC - Projeto de Avaliação da PCDF

repo_name: 2022.2-PCDF
repo_url: https://github.com/Interacao-Humano-Computador/2022.2-PCDF

theme:
  name: material
  logo: assets/icons/logo-pcdf.png
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Planejamento:
      - Escolha do site: escolha_do_site.md
      - Cronograma: cronograma.md
      - Processo de design: processo_de_design.md
      - Ferramentas: ferramentas.md
  - Análise de Requisitos:
    - Perfil de Usuário: analise-de-requisitos/user_profile.md
  - Reuniões:
    - Reunião01: Atas/Ata1.md
    - Reunião02: Atas/Ata2.md
    - Reunião03: Atas/Ata3.md
  - Apresentações:
    - Apresentação-1: apresentacoes/apresentacao-01.md 
